### DISCUSSION TITLE
Appending map object data inside an array within Firestore (Swift / iOS)

### DISCUSSION THREAD

**Discussion by haIIux** [firebase/firebase-ios-sdk#10040] [Q&A]
I'm not sure the best method to ask this question but I'm going to go for it... I am building out an application which I am using Firestore for. The data is arranged as follows within the Firestore website interface and accepts without issue and also reads without issue, it's the writing that is the problem.
```
cozys:
      0: 
          name: String
          url: String
          tags: [String]?
          notes: String?
      1:
         name: String
         url: String
         tags: [String]?
         notes: String?
```
As you can see, `cozys` is an array and the objects within, are a Firestore map. I've tried a few methods to get this to work which you will find below. 

```
/// This throws an error indicating that nested arrays are unsupported. I assumed that is because I'm trying to add the tags array. 
.setData(
    [
       "cozys": FieldValue.arrayUnion(
          [
             "name": name
             "url": url
             "tags": tags
             "notes": notes
          ]
    ]
)
```

```
/// This will just append the data in an array, not as a map object as I need and will not accept my array.
.setData(
    [
       "cozys": FieldValue.arrayUnion(
          [
             name
             url
              notes
          ]
    ]
)
```

I visited [this link via the docs](https://cloud.google.com/firestore/docs/manage-data/add-data#custom_objects) and attempted to do it that way as well which yielded the error below the code snippet.
```
        let appendData = Model(
            name: name,
//            tags: tags,
            url: url,
            notes: notes)

                    .setData(
                        [
                            "cozys": FieldValue.arrayUnion([appendData])
                        ], merge: true
                    )
```
>*** Terminating app due to uncaught exception 'FIRInvalidArgumentException', reason: 'Unsupported type: __SwiftValue'
terminating with uncaught exception of type NSException
