### ISSUE TITLE
UI API called on a background thread: -[UIApplication statusBarOrientation]

### ISSUE THREAD

**Issue by wongzigii** [firebase/firebase-ios-sdk#10984]
### Description

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/7384288/226902373-bd202b7a-210e-4e72-bed3-918e90f9cf27.png">

### Firebase SDK Version

8.15.0

### Xcode Version

14.2 (14C18)

### Installation Method

CocoaPods

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarOrientation]
PID: 7631, TID: 1104100, Thread name: (none), Queue name: com.apple.NSURLSession-delegate, QoS: 0
Backtrace:
4   FirebaseCrashlytics                 0x0000000103ee5d04 -[FIRCLSNotificationManager captureInitialNotificationStates] + 80
5   FirebaseCrashlytics                 0x0000000103ee5bb4 -[FIRCLSNotificationManager registerNotificationListener] + 24
6   FirebaseCrashlytics                 0x0000000103eeab70 -[FIRCLSReportManager startCrashReporterWithProfilingMark:report:] + 120
7   FirebaseCrashlytics                 0x0000000103eea0a8 -[FIRCLSReportManager startWithProfilingMark:] + 244
8   FirebaseCrashlytics                 0x0000000103ef3724 -[FIRCrashlytics initWithApp:appInfo:installations:analytics:] + 892
9   FirebaseCrashlytics                 0x0000000103ef3b70 __38+[FIRCrashlytics componentsToRegister]_block_invoke + 280
10  FirebaseCore                        0x0000000103aa3ae8 -[FIRComponentContainer instantiateInstanceForProtocol:withBlock:] + 68
11  FirebaseCore                        0x0000000103aa3c60 -[FIRComponentContainer instanceForProtocol:] + 184
12  FirebaseCore                        0x0000000103aa39f4 -[FIRComponentContainer instantiateEagerComponents] + 160
13  FirebaseCore                        0x0000000103aa0c88 +[FIRApp configureWithName:options:] + 608
14  FirebaseCore                        0x0000000103aa097c +[FIRApp configureWithOptions:] + 80
15  FirebaseCore                        0x0000000103aa0918 +[FIRApp configure] + 100
16  hebaoapp                            0x00000001011892cc $s8hebaoapp11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtFySbcfU_ySbcfU_ + 776
17  hebaoapp                            0x00000001010650d4 $s8hebaoapp21WalletCoreDataManagerC20setupFromNewKeychain14completeHandleyySbc_tFySayAA15ContractVersionVGSg_AA8APIErrorOSgtcfU_Tf4ndnnnn_n + 1480
18  hebaoapp                            0x0000000100a04f20 $s8hebaoapp21WalletCoreDataManagerC20setupFromNewKeychain14completeHandleyySbc_tFySayAA15ContractVersionVGSg_AA8APIErrorOSgtcfU_TA + 40
19  hebaoapp                            0x0000000100a07030 $s8hebaoapp10AmmMarketsVSgAA8APIErrorOSgIeggg_AdGIegng_TRTA + 24
20  hebaoapp                            0x0000000100958e6c $s8hebaoapp15HebaoAPIRequestC3get10parameters8endpoint6apiKey0G7SigType010specialApiI010forRecover17completionHandlerySDyS2SG_S2SSgAA0liJ0OAMSbyxSg_AA8APIErrorOSgtctSeRzSERzlFZy10Foundation4DataVSg_So13NSURLResponseCSgAStcfU_Tf2nnnninnnn_nSayAA016LatestTokenPriceS0VG_Tg5Tm + 2188
21  hebaoapp                            0x00000001009d16a4 $s8hebaoapp15HebaoAPIRequestC3get10parameters8endpoint6apiKey0G7SigType010specialApiI010forRecover17completionHandlerySDyS2SG_S2SSgAA0liJ0OAMSbyxSg_AA8APIErrorOSgtctSeRzSERzlFZy10Foundation4DataVSg_So13NSURLResponseCSgAStcfU_Tf2nnnninnnn_nSayAA11TrustDetailVG_Tg5TATm + 64
22  hebaoapp                            0x00000001009fffdc $s8hebaoapp15HebaoAPIRequestC3get10parameters8endpoint6apiKey0G7SigType010specialApiI010forRecover17completionHandlerySDyS2SG_S2SSgAA0liJ0OAMSbyxSg_AA8APIErrorOSgtctSeRzSERzlFZy10Foundation4DataVSg_So13NSURLResponseCSgAStcfU_Tf2nnnninnnn_nSayAA15ContractVersionVG_Tg5TA + 44
23  hebaoapp                            0x00000001007b7d78 $s8hebaoapp7RequestC22responseHandlerResultsyy10Foundation4DataVSg_So13NSURLResponseCSgs5Error_pSgyAH_AkA8APIErrorOSgtctFZTf4nnnnd_n + 928
24  hebaoapp                            0x00000001007b6a38 $s8hebaoapp7RequestC3get_10parameters6apiKey0E3Sig17completionHandlerySS_SDyS2SGSSSgAJy10Foundation4DataVSg_So13NSURLResponseCSgAA8APIErrorOSgtctFZyAN_AQs5Error_pSgtYbcfU0_ + 380
25  hebaoapp                            0x00000001007b59f4 $s10Foundation4DataVSgSo13NSURLResponseCSgs5Error_pSgIeghggg_So6NSDataCSgAGSo7NSErrorCSgIeyBhyyy_TR + 148
26  CFNetwork                           0x00000001c733e05c CFURLRequestSetMainDocumentURL + 2972
27  CFNetwork                           0x00000001c734dfb4 _CFNetworkErrorCopy2023-03-22 20:05:00.482958+0800 hebaoapp[7631:1104100] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarOrientation]
PID: 7631, TID: 1104100, Thread name: (none), Queue name: com.apple.NSURLSession-delegate, QoS: 0
Backtrace:
4   FirebaseCrashlytics                 0x0000000103ee5d04 -[FIRCLSNotificationManager captureInitialNotificationStates] + 80
5   FirebaseCrashlytics                 0x0000000103ee5bb4 -[FIRCLSNotificationManager registerNotificationListener] + 24
6   FirebaseCrashlytics                 0x0000000103eeab70 -[FIRCLSReportManager startCrashReporterWithProfilingMark:report:] + 120
7   FirebaseCrashlytics                 0x0000000103eea0a8 -[FIRCLSReportManager startWithProfilingMark:] + 244
8   FirebaseCrashlytics                 0x0000000103ef3724 -[FIRCrashlytics initWithApp:appInfo:installations:analytics:] + 892
9   FirebaseCrashlytics                 0x0000000103ef3b70 __38+[FIRCrashlytics componentsToRegister]_block_invoke + 280
10  FirebaseCore                        0x0000000103aa3ae8 -[FIRComponentContainer instantiateInstanceForProtocol:withBlock:] + 68
11  FirebaseCore                        0x0000000103aa3c60 -[FIRComponentContainer instanceForProtocol:] + 184
12  FirebaseCore                        0x0000000103aa39f4 -[FIRComponentContainer instantiateEagerComponents] + 160
13  FirebaseCore                        0x0000000103aa0c88 +[FIRApp configureWithName:options:] + 608
14  FirebaseCore                        0x0000000103aa097c +[FIRApp configureWithOptions:] + 80
15  FirebaseCore                        0x0000000103aa0918 +[FIRApp configure] + 100
16  hebaoapp                            0x00000001011892cc $s8hebaoapp11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtFySbcfU_ySbcfU_ + 776
17  hebaoapp                            0x00000001010650d4 $s8hebaoapp21WalletCoreDataManagerC20setupFromNewKeychain14completeHandleyySbc_tFySayAA15ContractVersionVGSg_AA8APIErrorOSgtcfU_Tf4ndnnnn_n + 1480
18  hebaoapp                            0x0000000100a04f20 $s8hebaoapp21WalletCoreDataManagerC20setupFromNewKeychain14completeHandleyySbc_tFySayAA15ContractVersionVGSg_AA8APIErrorOSgtcfU_TA + 40
19  hebaoapp                            0x0000000100a07030 $s8hebaoapp10AmmMarketsVSgAA8APIErrorOSgIeggg_AdGIegng_TRTA + 24
20  hebaoapp                            0x0000000100958e6c $s8hebaoapp15HebaoAPIRequestC3get10parameters8endpoint6apiKey0G7SigType010specialApiI010forRecover17completionHandlerySDyS2SG_S2SSgAA0liJ0OAMSbyxSg_AA8APIErrorOSgtctSeRzSERzlFZy10Foundation4DataVSg_So13NSURLResponseCSgAStcfU_Tf2nnnninnnn_nSayAA016LatestTokenPriceS0VG_Tg5Tm + 2188
21  hebaoapp                            0x00000001009d16a4 $s8hebaoapp15HebaoAPIRequestC3get10parameters8endpoint6apiKey0G7SigType010specialApiI010forRecover17completionHandlerySDyS2SG_S2SSgAA0liJ0OAMSbyxSg_AA8APIErrorOSgtctSeRzSERzlFZy10Foundation4DataVSg_So13NSURLResponseCSgAStcfU_Tf2nnnninnnn_nSayAA11TrustDetailVG_Tg5TATm + 64
22  hebaoapp                            0x00000001009fffdc $s8hebaoapp15HebaoAPIRequestC3get10parameters8endpoint6apiKey0G7SigType010specialApiI010forRecover17completionHandlerySDyS2SG_S2SSgAA0liJ0OAMSbyxSg_AA8APIErrorOSgtctSeRzSERzlFZy10Foundation4DataVSg_So13NSURLResponseCSgAStcfU_Tf2nnnninnnn_nSayAA15ContractVersionVG_Tg5TA + 44
23  hebaoapp                            0x00000001007b7d78 $s8hebaoapp7RequestC22responseHandlerResultsyy10Foundation4DataVSg_So13NSURLResponseCSgs5Error_pSgyAH_AkA8APIErrorOSgtctFZTf4nnnnd_n + 928
24  hebaoapp                            0x00000001007b6a38 $s8hebaoapp7RequestC3get_10parameters6apiKey0E3Sig17completionHandlerySS_SDyS2SGSSSgAJy10Foundation4DataVSg_So13NSURLResponseCSgAA8APIErrorOSgtctFZyAN_AQs5Error_pSgtYbcfU0_ + 380
25  hebaoapp                            0x00000001007b59f4 $s10Foundation4DataVSgSo13NSURLResponseCSgs5Error_pSgIeghggg_So6NSDataCSgAGSo7NSErrorCSgIeyBhyyy_TR + 148
26  CFNetwork                           0x00000001c733e05c CFURLRequestSetMainDocumentURL + 2972
27  CFNetwork                           0x00000001c734dfb4 _CFNetworkErrorCopy
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

- Firebase/AnalyticsWithoutAdIdSupport (8.15.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics/WithoutAdIdSupport (~> 8.15.0)
  - Firebase/CoreOnly (8.15.0):
    - FirebaseCore (= 8.15.0)
  - Firebase/Crashlytics (8.15.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 8.15.0)
  - FirebaseAnalytics/WithoutAdIdSupport (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
  - FirebaseCore (8.15.0):
    - FirebaseCoreDiagnostics (~> 8.0)
  - FirebaseCoreDiagnostics (8.15.0):
  - FirebaseCrashlytics (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
  - FirebaseInstallations (8.15.0):
    - FirebaseCore (~> 8.0)
  - Firebase/AnalyticsWithoutAdIdSupport
  - Firebase/Crashlytics
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCrashlytics
    - FirebaseInstallations
  Firebase: 5f8193dff4b5b7c5d5ef72ae54bb76c08e2b841d
  FirebaseAnalytics: 7761cbadb00a717d8d0939363eb46041526474fa
  FirebaseCore: 5743c5785c074a794d35f2fff7ecc254a91e08b1
  FirebaseCoreDiagnostics: 92e07a649aeb66352b319d43bdd2ee3942af84cb
  FirebaseCrashlytics: feb07e4e9187be3c23c6a846cce4824e5ce2dd0b
  FirebaseInstallations: 40bd9054049b2eae9a2c38ef1c3dd213df3605cd

```

</details>
