### ISSUE TITLE
Firebase significantly contributes to iOS app launch time

### ISSUE THREAD

**Issue by mkj-is** [firebase/firebase-ios-sdk#13232]
### Description

In [Xcode Organizer in Xcode 16 beta](https://developer.apple.com/wwdc24/10135?time=573) we see Firebase is contributing 10 % to our app launch time, which is concerning.

Our custom measurements in production show the P90 for initialising Firebase SDK is 90 ms, P50 is 40 ms. We are using CocoaPods, but Firebase is statically linked.

These methods are responsible:

- **3 %: FIRCLSContextInitialize + 876** (130 ms spent in this code path during a 1792 ms launch)
- **2 %: __46+[APMAnalytics startWithAppID:origin:options:]_block_invoke + 1148** (90 ms spent in this code path during a 1220 ms launch)
- **2 %: +[APMAEU appStoreRURL] + 160** (90 ms spent in this code path during a 3528 ms launch)
- **1 %: -[APMUserDefaults objectForKey:] + 88** (90 ms spent in this code path during a 1186 ms launch)
- **1 %: -[FIRInstallationsAPIService initWithAPIKey:projectID:heartbeatLogger:] + 92** (60 ms spent in this code path during a 1830 ms launch)
- **1 %: APMIsScreenReportingEnabled + 28** (130 ms spent in this code path during a 2467 ms launch)

Might be related to https://github.com/firebase/firebase-ios-sdk/issues/13223.

<img width="1157" alt="Screenshot 2024-07-04 at 13 04 54" src="https://github.com/firebase/firebase-ios-sdk/assets/708312/78c4c630-d84a-4626-ae95-e4750230804d">
<img width="1156" alt="Screenshot 2024-07-04 at 13 05 01" src="https://github.com/firebase/firebase-ios-sdk/assets/708312/a6d182b0-a784-4f90-a331-6168b78549f6">
<img width="1156" alt="Screenshot 2024-07-04 at 13 05 16" src="https://github.com/firebase/firebase-ios-sdk/assets/708312/412f4913-7429-4544-802b-a8c5c36e9814">
<img width="1157" alt="Screenshot 2024-07-04 at 13 05 31" src="https://github.com/firebase/firebase-ios-sdk/assets/708312/c623eaa5-f098-4d00-9fbb-adbb474a3a48">
<img width="1154" alt="Screenshot 2024-07-04 at 13 05 42" src="https://github.com/firebase/firebase-ios-sdk/assets/708312/fa4a9c42-2326-41f3-9e81-dedeb4c561db">
<img width="1156" alt="Screenshot 2024-07-04 at 13 07 33" src="https://github.com/firebase/firebase-ios-sdk/assets/708312/94dfcfc1-f15a-41c9-9018-e0b5e8e0fc21">

### Reproducing the issue

Open Xcode Organizer (Xcode 16 beta) Launch reports for any app with significant number of users and see the stats. 

### Firebase SDK Version

10.22

### Xcode Version

16.0

### Installation Method

CocoaPods

### Firebase Product(s)

Crashlytics, Performance

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml
  FirebaseABTesting: e6e3c3e0e35813874f571d1b7bdae2aab319dd38
  FirebaseAnalytics: 8d0ff929c63b7f72260f332b86ccf569776b75d3
  FirebaseCore: 0326ec9b05fbed8f8716cddbf0e36894a13837f7
  FirebaseCoreExtension: 8a47811d0b155501559ef05d089518152a0a1677
  FirebaseCoreInternal: 910a81992c33715fec9263ca7381d59ab3a750b7
  FirebaseCrashlytics: e568d68ce89117c80cddb04073ab9018725fbb8c
  FirebaseInstallations: 91950fe859846fff0fbd296180909dd273103b09
  FirebaseMessaging: 9f71037fd9db3376a4caa54e5a3949d1027b4b6e
  FirebasePerformance: 095debad1fc8d7d73148a835fcaec9e528946166
  FirebaseRemoteConfig: 9f3935cefecd85d5b312192117f444957de24a75
  FirebaseRemoteConfigInterop: b25018791b204c0d78a90e394d6c62d9b1f22da8
  FirebaseSessions: c0939656253a1fa0e94ecc266ccf770cc8b33732
  FirebaseSharedSwift: 0274086954b1b2d5fd7e829eccc587044d72a4ba
```

</details>
