### ISSUE TITLE
Firebase Firestore not setting data using Cocoapods Rome dependencies + Xcodegen

### ISSUE THREAD

**Issue by DrewKiino** [firebase/firebase-ios-sdk#3432]
### [READ] Step 1: Are you in the right place?

yes.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1 
  * Firebase SDK version: 6.5.0
  * Firebase Component: Firestore
  * Component version: 6.5.0

### [REQUIRED] Step 3: Describe the problem

I used [Rome](https://github.com/CocoaPods/Rome) to download and build the external frameworks I needed for Firebase. This is what I have in my pod file
```
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
```

then I used [Xcodegen](https://github.com/yonaskolb/XcodeGen) to generate the project with firebase as a targets template.
```yml
targets:
  Firebase2:
    transitivelyLinkDependencies: true
    dependencies:
      - {embed: false, framework: Rome/FIRAnalyticsConnector.framework}
      - {embed: false, framework: Rome/FirebaseAnalytics.framework}
      - {embed: false, framework: Rome/FirebaseCore.framework}
      - {embed: false, framework: Rome/FirebaseCoreDiagnostics.framework}
      - {embed: false, framework: Rome/FirebaseFirestore.framework}
      - {embed: false, framework: Rome/FirebaseInstanceID.framework}
      - {embed: false, framework: Rome/GoogleAppMeasurement.framework}
      - {embed: true, framework: Rome/GoogleUtilities.framework}
      - {embed: true, framework: Rome/grpc.framework}
      - {embed: true, framework: Rome/grpcpp.framework}
      - {embed: true, framework: Rome/leveldb.framework}
      - {embed: true, framework: Rome/nanopb.framework}
      - {embed: true, framework: Rome/openssl_grpc.framework}
      - {embed: false, framework: Rome/Protobuf.framework}
```
you can see that some are embedded and some are not, I followed the manual import outlined in the firebase website.

I ran my view controller with this code
```swift
func viewDidLoad() {
    FirebaseConfiguration.shared.setLoggerLevel(.max)

    Firestore.enableLogging(true)
    
//    Auth.auth().createUser(withEmail: "drew@gmail.com", password: "testpass") { result, error in
//      if let error = error {
//        print(error)
//      } else if let result = result {
//        print(result)
//      }
//    }

    let docData: [String: Any] = [
      "stringExample": "Hello world!",
      "booleanExample": true,
      "numberExample": 3.14159265,
      "dateExample": Timestamp(date: Date()),
      "arrayExample": [5, true, "hello"],
      "nullExample": NSNull(),
      "objectExample": [
        "a": 5,
        "b": [
          "nested": "foo"
        ]
      ]
    ]

    print("Writing documents")

    firestore.collection("data").getDocuments { snapshot, error in
      if let error = error {
        print(error)
      } else if let snapshop = snapshot {
        print(snapshop)
      }
    }
}
```
basically uncommenting `Auth` I actually get a response back so I know for sure it's just `Firestore`. So when I run this code, I get `Writing Documents` but never a call back for the inner prints. 

I did logging and enabling OS_ACTIVITY_MODE and I don't see any prints whatsoever.
It's like the function itself never gets called at all. I can't really put break points in the SDK itself because it's framework based and all I get are headers. 

need some help here :(

#### Steps to reproduce:

1. make a dummy project and an associated firebase app with the plist
2. pod install using Rome to create your frameworks using the above podspec
3. use xcodegen to link the dependencies and generate the xcodeproject
4. use the above code and try to set data into firebase
5. see that it's not doing it?????

**Comment by paulb777** [comment]
Please confirm that the `-ObjC` flag was added to "Other Linker Flags" in `Build Settings`

**Comment by DrewKiino** [comment]
@paulb777 okay that did the trick! I added it and it was able to compile for me and showed me which other libraries I ended up missing.

this is my template for anyone interested.

```
targetTemplates:
  Firebase:
    transitivelyLinkDependencies: true
    requiresObjCLinking: true
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
      OTHER_LDFLAGS: $(inherited) -ObjC
    dependencies:
      - sdk: libc++.tbd
      - sdk: libsqlite3.tbd
      - sdk: Storekit.framework
      - sdk: SystemConfiguration.framework
      - {embed: false, framework: Rome/FIRAnalyticsConnector.framework}
      - {embed: false, framework: Rome/FirebaseAnalytics.framework}
      - {embed: false, framework: Rome/FirebaseCore.framework}
      - {embed: false, framework: Rome/FirebaseCoreDiagnostics.framework}
      - {embed: false, framework: Rome/FirebaseFirestore.framework}
      - {embed: false, framework: Rome/FirebaseInstanceID.framework}
      - {embed: false, framework: Rome/GoogleAppMeasurement.framework}
      - {embed: true, framework: Rome/GoogleUtilities.framework}
      - {embed: true, framework: Rome/grpc.framework}
      - {embed: true, framework: Rome/grpcpp.framework}
      - {embed: true, framework: Rome/leveldb.framework}
      - {embed: true, framework: Rome/nanopb.framework}
      - {embed: true, framework: Rome/openssl_grpc.framework}
      - {embed: true, framework: Rome/Protobuf.framework}
      - {embed: true, framework: Rome/GTMSessionFetcher.framework}
```
