### ISSUE TITLE
[Crashlytics] upload-symbols fails with "illegal instruction: 4" on Travis CI

### ISSUE THREAD

**Issue by SebastianThiebaud** [firebase/firebase-ios-sdk#5526]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1 (11E503a)
  * Firebase SDK version: 6.23.0
  * Firebase Component: Core, Analytics, Crashlytics, Performance
  * Component version: 6.23.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

The `upload-symbols` command fails when trying to upload the symbols. This is happening on Travis-CI using Fastlane.

```
/Users/travis/build/org/repo/Pods/FirebaseCrashlytics/upload-symbols -ai 1:#######:ios:####### -d -p ios SomeApplication.app.dSYM.zip
```

```
upload-symbols 3.3 build 22

Arguments:
Debug mode enabled
Google App ID: 1:#######:ios:#######
Platform: ios
DSYM Paths: ["SomeApplication.app.dSYM.zip"]

Fetching upload-symbols settings...
Inspecting next path: SomeApplication.app.dSYM.zip
Found archive at path: SomeApplication.app.dSYM.zip
Inspecting next path: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T//SomeApplication.app.dSYM.zip.unzipped/TwilioChatClient.framework.dSYM
Found dSYM at path: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T//SomeApplication.app.dSYM.zip.unzipped/TwilioChatClient.framework.dSYM
Begin processing dSYM at /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T//SomeApplication.app.dSYM.zip.unzipped/TwilioChatClient.framework.dSYM
Illegal instruction: 4
```

**Comment by samedson** [comment]
Hey @SebastianThiebaud sorry you're running into this. This type of error usually shows up when macOS binaries are running on old mac hardware.

Here's a related old stackoverflow: https://stackoverflow.com/questions/48333342/os-x-illegal-instruction-4-in-travis-ci

Does this happen on all runs of your build, and does Travis provide a way for you to run on newer hardware?

**Comment by SebastianThiebaud** [comment]
Hi @samedson 

Thank you for your response. We're already running on the newest macOS image (xcode11.4). You can check the details of the image on Travis-CI here: https://docs.travis-ci.com/user/reference/osx/#macos-version

And yes, it does happen on all our build. If you have any suggestions or can provide more details on what should need updated, maybe I can communicate with Travis-CI support (it seems unlikely they would change anything though).

**Comment by samedson** [comment]
So I tried building a sample app and running upload-symbols on its dSYM in Travis, and it worked without an illegal instruction error.

Here's the .travis.yml file: https://github.com/samedson/travis-test-crashlytics/blob/master/.travis.yml

```
os: osx
osx_image: xcode11.4

jobs:
  include:
  - name: "Fabric Upload Symbols"
    script: ./upload-symbols-fabric -p ios --gsp ./GoogleService-Info.plist -- CrashlyticsExample.app.dSYM --debug
  - name: "Firebase Upload Symbols"
    script: ./upload-symbols-firebase -p ios --gsp ./GoogleService-Info.plist -- CrashlyticsExample.app.dSYM --debug

```

I wonder if there's something about the dSYM, or some combination of parameters to upload-symbols. The other option is there are certain machines Travis is running that could have hardware issues, but that seems less likely since you said it happens on every run.
